### PR TITLE
AUD-1736 Add local setup instructions to README

### PR DESCRIPTION
**Pull request by balderdash**
Fixes: https://auderenow.atlassian.net/browse/AUD-1736

**Reviewer should merge**
* No

### CODE REVIEW

**Review by jcmorrow — COMMENTED** [review]
When I run `npm run start` on my fresh install I get:

```
Failed to compile.

./src/transport/firestore.ts
Module not found: Can't resolve './firebaseconfig.json' in '/Users/josh/code/maisha/flows/src/transport'
```

Where do I get a `firebaseconfig.json` from?

**Comment by balderdash** [comment]
@jcmorrow  You shouldn't need a firebaseconfig.json, since we're not using any of the firebase APIs. Mind pulling this branch and trying again?

I switched to [firebase sdk auto-configuration](https://firebase.google.com/docs/hosting/reserved-urls#sdk_auto-configuration) so that we don't need to use `firebaseconfig.json` even if running in firebase mode, in case that's ever useful.

**Comment by jcmorrow** [comment]
I think this is *probably* unrelated but now I'm getting this error from `npm run start`:

```
/Users/josh/code/maisha/flows/src/Screens/TaskPanel.tsx
TypeScript error in /Users/josh/code/maisha/flows/src/Screens/TaskPanel.tsx(470,15):
No overload matches this call.
  Overload 2 of 2, '(props: DateRangePickerShape, context?: any): Component<DateRangePickerShape, any, any>', gave the following error.
    Type 'import("/Users/josh/code/maisha/flows/node_modules/moment/moment").Moment | null' is not assignable to type 'moment.Moment | null'.
      Type 'import("/Users/josh/code/maisha/flows/node_modules/moment/moment").Moment' is not assignable to type 'moment.Moment'.
  Overload 2 of 2, '(props: DateRangePickerShape, context?: any): Component<DateRangePickerShape, any, any>', gave the following error.
    Type 'import("/Users/josh/code/maisha/flows/node_modules/moment/moment").Moment | null' is not assignable to type 'moment.Moment | null'.
      Type 'import("/Users/josh/code/maisha/flows/node_modules/moment/moment").Moment' is not assignable to type 'moment.Moment'.
  Overload 2 of 2, '(props: DateRangePickerShape, context?: any): Component<DateRangePickerShape, any, any>', gave the following error.
    Type '({ startDate, endDate, }: { startDate: Moment | null; endDate: Moment | null; }) => void' is not assignable to type '(arg: { startDate: Moment | null; endDate: Moment | null; }) => void'.  TS2769

    468 |             <div className="mainview_padded_row">Date Range: </div>
    469 |             <div className="mainview_date_picker">
  > 470 |               <DateRangePicker
        |               ^
    471 |                 startDate={searchDates.startDate}
    472 |                 startDateId={"startDate"}
    473 |                 endDate={searchDates.endDate}
```

**Comment by balderdash** [comment]
Hmm, I haven't been able to repro this. A couple things to look into:
* After you ran `yarn`, did git notice any modifications to the `yarn.lock` file?
* I'm not sure how, but it seems like you're ending up with multiple versions of `moment`. Try running `find . -name moment` in your `node_modules` folder and let me know what you see
* You can always try blowing everything away and trying again: `rm -rf node_modules && yarn cache clean && yarn`

**Comment by jcmorrow** [comment]
Ah, yeah, turns out `npm` and `yarn` are not as interchangeable as I had thought. Installing and using `yarn` worked for me 👍

**Review by jcmorrow — APPROVED** [review]

**Pull request merged**
